- name: PHPUnit (graychen)
  # You may pin to the exact commit or the version.
  # uses: Graychen/phpunit-action@026f8104f1a6b5bc646df2d495bc8b34080c3e03
  uses: Graychen/phpunit-action@v1.0.0
  with:
    # Configuration file location
    config: # optional, default is phpunit.xml.dist
